### ISSUE TITLE
Test killing a hero with a hero power

### ISSUE THREAD

**Issue by jleclanche** [jleclanche/fireplace#142]
It seems to not schedule a death. It would explain @beheh's issues with inspire too.

**Comment by beheh** [comment]
Death processing in Fireplace is very wonky after looking into this in depth for a while. We're not honoring the "death processing only when outermost phase is complete" rule at all, so we might need to think about evaluating `source` to decide if we're an outermost action.

Also, a lot of the basic phase test cases from the Advanced Rulebook page fail, such as playing Flamestrike with an Acolyte on the board and 3 enemy Explosive Sheeps - we'd expect 3 card draws, but since the deathrattle in fireplace currently triggers a death sweep (even though they're within a death sweep themselves) the Acolyte is already removed after two draws.

**Comment by jleclanche** [comment]
Hero Power needs to queue an `Activate()` action which is currently unimplemented; like Play().
