### ISSUE TITLE
RandomCollectible can return heroes

### ISSUE THREAD

**Issue by benikm91** [jleclanche/fireplace#205]
Hey

While developing a hearthstone bot I came across this issue:

When the random AI played the minion 'Grand Crusader' in fireplace, he got the paladin card \<Hero 'Uther Lightbringer'\>. I belive that's because heroes also are cards in fireplace, but this is not be possible in Hearthstone.

Here the data from my (special) logfile:

INFO:fireplace:Player1 plays \<Minion ('Grand Crusader') ATK:5 HP:5 FLAGS:0000\>
INFO:fireplace:New Game state: [...] PlayerHand<[[...], \<Hero ('Uther Lightbringer')\>], [...]
INFO:fireplace:Player1 plays \<Hero ('Uther Lightbringer')\>

Regards
Benjamin Meyer

**Comment by beheh** [comment]
Thanks for your report. I assume heroes are defined as collectible in the HS-data files, and this might also occur with Hunter and Lock-and-Load. There are a few ways of fixing it, but the main developer (jleclanche) is currently not available for a few more weeks or so. I might be able to catch him sometime inbetween and then discuss and fix this.

**Comment by beheh** [comment]
So, this is a bit more complicated since our evaluator system is pretty greedy: once you specificy for example class as Paladin - and even if you specifically only grab collectible cards - the heroe applies due to it being defined that way in the actual game files we import. There is also no way to exclude certain types or to combine them yet, so we can't exclude hero types or only include Weapons + Minions + Spells.

There is no easy fix for this immediately, but I'll see what I can do.

**Comment by beheh** [comment]
Fixed by internally explicitely filtering for Minions, Weapons and Spells (default, can be overridden).
