### ISSUE TITLE
NotifyOfCardGained is not logged

### ISSUE THREAD

**Issue by pabloperezromani** [jleclanche/fireplace#236]
Achievements.log doesn't log NotifyOfCardGained events anymore. Can pack openings be logged in any other way?

**Comment by jleclanche** [comment]
Nope. I looked into this the other day and there's nothing else that can get opened packs, short of hooking into the dll. Best bet is to ask blizzard.

Closing this because this is a hearthstone simulator that has nothing to do with the client. check out http://hearthsim.info if you want to chat about these things, we have an irc channel.
