### ISSUE TITLE
Fencing Coach deducts mana past 0

### ISSUE THREAD

**Issue by beheh** [jleclanche/fireplace#369]
Player was at 0 mana.
Played Fencing Coach, Heropower cost 0 mana.
After playing Hero Power, player mana was at -2.

**Comment by cdennison** [comment]
Verified the issue with this test:
	game = prepare_game()
	coach = game.player1.give("AT_115")
	coach.play()
	game.player1.hero.power.use()
	print(game.player1.mana)
        >> 5 mana instead of 7

The flow for hero power (which doesn’t work for fencing coach):
game.player1.hero.power.use()
	Card.HeroPower.Use
		actions->Activate.do
		After action…
		self.controller.used_mana += self.cost (i.e. pay_cost)

For fencing coach the event is: 
Activate(CONTROLLER, HERO_POWER).on(Destroy(SELF))
Which resolves after activate and before the pay_cost

The flow for spells e.g. preparation followed by fireball (which does work)
game.player1.give("…").play()
	Card.play
		actions->Play.do
		Inside Play.do… 
		player.pay_cost(…)

So I think the fix is to:
1. Refactor Hero Power to also use player.pay_cost for consistency
2. Move the pay_cost call inside the Activate.do

If one of the committers agrees with this approach I’d like to fix the code and submit a pull request.

**Comment by NightKev** [comment]
@cdennison Seems like it makes sense. You should hop on irc.freenode.net #hearthsim if you want to talk with the people who manage the repo (such as @jleclanche or @beheh (B_E on irc)).

**Comment by NightKev** [comment]
That causes it to go away at the end of the turn.
