### ISSUE TITLE
Dragon Consort wrong selector

### ISSUE THREAD

**Issue by tylorr** [jleclanche/fireplace#423]
Doesn't look like Dragon Consort is implemented correctly. It's supposed to buff only Dragons in your hand but it's currently using:

```
play = Buff(CONTROLLER, "BRM_018e")
```

Or am I not understanding something?

**Comment by smallnamespace** [comment]
Yes, the cost buff is -3 instead of the -2 on the card and there are no tests. Actually the buff applies to all dragons, including ones not drawn yet.

**Comment by jleclanche** [comment]
That's because `BRM_018e` is a buff *on the controller*, which creates a cost reduction buff for the dragons in your hand.

https://github.com/jleclanche/fireplace/blob/83b06c58dc8faf4b56ce78c153a16fc7e6b0e506/fireplace/cards/blackrock/collectible.py#L70-L74

It's definitely implemented wrong though.

Development on fireplace is on hold for the time being though. I will get back to it at some point, promise :)

**Comment by tylorr** [comment]
Yeah, I think I understand now. Preparation has a similar mechanic and looks to be implemented correctly.
