### ISSUE TITLE
entity id question

### ISSUE THREAD

**Issue by hstoner009** [jleclanche/fireplace#53]
Hey,

I noticed there are a variety of id's in place to keep track of entities. It looks like there are uuid and something like entity.manager.id. I would like to use entity.manager.id to keep track of entities for purposes of knowing 'CONTROLLER' and 'ATTACHED' etc.; however, it looks like the manager.id is only generated during a player.give(...) and not during player.draw(...). So the manager.id's are not assigned for the player's hand. Was this intentional and if so, is there an alternative way to know an entity's id?

**Comment by jleclanche** [comment]
Some context first: The manager is there so that external observers (such as a match server) may know when a new entity (of any kind) is created.

Creating a card through game.card(id) will call `manager.new_entity()`. Observers can then hook that and react when a new entity is created. While it's technically possible to do Card(id), if you have observers that will break them - it's only there for simple testing.

When a player draws a card, the card is moved from the DECK zone to the HAND zone. So no new entity is created because the entity should already exist, merely hidden from the player's view. The cards in the deck are created when the game is started, and are supposed to call manager.new_entity() *there*. However it looks like I might have lost that when I rewrote the game.start(). I'll look into it.
